#!/usr/bin/env node
/**
 * Migrate data/index.json + data/accounts.json into D1 SQL batches.
 * Usage:
 *   node scripts/seed-d1.mjs --write scripts/seed-generated.sql
 *   node scripts/seed-d1.mjs --local   # apply to local D1 via wrangler
 *   node scripts/seed-d1.mjs --remote  # apply to remote D1 (requires auth)
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const catalog = JSON.parse(
  readFileSync(join(root, "data/index.json"), "utf8"),
);
const accountsDoc = JSON.parse(
  readFileSync(join(root, "data/accounts.json"), "utf8"),
);

function sqlString(value) {
  if (value == null) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

const statements = [];

statements.push(
  `INSERT INTO catalog_meta (key, value) VALUES ('version', ${sqlString(catalog.version)}) ON CONFLICT(key) DO UPDATE SET value = excluded.value;`,
);
statements.push(
  `INSERT INTO catalog_meta (key, value) VALUES ('updatedAt', ${sqlString(catalog.updatedAt)}) ON CONFLICT(key) DO UPDATE SET value = excluded.value;`,
);

for (const scan of catalog.scans) {
  statements.push(
    `INSERT INTO scans (id, scan_date, title, sources_json, notes) VALUES (${sqlString(scan.id)}, ${sqlString(scan.date)}, ${sqlString(scan.title)}, ${sqlString(JSON.stringify(scan.sources ?? []))}, ${sqlString(scan.notes ?? "")}) ON CONFLICT(id) DO UPDATE SET title = excluded.title, sources_json = excluded.sources_json, notes = excluded.notes;`,
  );
}

for (const article of catalog.articles) {
  const scanId = article.scanDate;
  const url = article.url ?? "";
  const hasDirect = article.hasDirectLink ? 1 : 0;
  statements.push(
    `INSERT INTO articles (
      id, scan_id, scan_date, channel, query, title, account, account_slug,
      published_label, summary, url, has_direct_link, source
    ) VALUES (
      ${sqlString(article.id)},
      ${sqlString(scanId)},
      ${sqlString(article.scanDate)},
      ${sqlString(article.channel ?? "")},
      ${sqlString(article.query ?? "")},
      ${sqlString(article.title)},
      ${sqlString(article.account ?? "")},
      NULL,
      ${sqlString(article.publishedLabel ?? "")},
      ${sqlString(article.summary ?? "")},
      ${sqlString(url)},
      ${hasDirect},
      ${sqlString("seed-json")}
    ) ON CONFLICT(id) DO UPDATE SET
      title = excluded.title,
      account = excluded.account,
      summary = excluded.summary,
      url = excluded.url,
      has_direct_link = excluded.has_direct_link;`,
  );
}

for (const account of accountsDoc.accounts) {
  statements.push(
    `INSERT INTO accounts (slug, name, added_at, notes) VALUES (${sqlString(account.slug)}, ${sqlString(account.name)}, ${sqlString(account.addedAt)}, ${sqlString(account.notes ?? "")}) ON CONFLICT(slug) DO UPDATE SET name = excluded.name, notes = excluded.notes;`,
  );
}

const sql = `-- generated by scripts/seed-d1.mjs\n${statements.join("\n")}\n`;
const outPath = join(root, "scripts/seed-generated.sql");

const args = process.argv.slice(2);
if (args.includes("--write") || (!args.includes("--local") && !args.includes("--remote"))) {
  writeFileSync(outPath, sql);
  console.log(`Wrote ${outPath} (${statements.length} statements)`);
}

if (args.includes("--local")) {
  writeFileSync(outPath, sql);
  execSync(
    `npx wrangler d1 execute track-scan-db --local --file=${outPath}`,
    { stdio: "inherit", cwd: root },
  );
}

if (args.includes("--remote")) {
  writeFileSync(outPath, sql);
  execSync(
    `npx wrangler d1 execute track-scan-db --remote --file=${outPath}`,
    { stdio: "inherit", cwd: root },
  );
}

console.log(
  "Note: a future ~49-url real catalog can re-run this script after replacing data/index.json.",
);
